# Generated by Django 3.1.2 on 2023-05-15 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cartitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='Carrito',
        ),
    ]
