# Generated by Django 3.1.2 on 2023-05-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_carrito_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
