# Generated by Django 3.1.2 on 2023-05-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20230515_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='carrito',
            name='antidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
