# Generated by Django 3.1.2 on 2023-05-16 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20230515_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='antidad',
            new_name='cantidad',
        ),
    ]
