# Generated by Django 3.1.2 on 2023-05-20 22:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0015_compra'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compra',
            new_name='historial',
        ),
    ]
