# Generated by Django 3.1.2 on 2023-05-20 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20230520_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='total',
        ),
    ]
