# Generated by Django 3.1.2 on 2023-05-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_historial_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='total',
            field=models.IntegerField(),
        ),
    ]
