# Generated by Django 3.1.2 on 2023-05-21 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_suscriptor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscriptor',
            name='donacion_mensual',
        ),
        migrations.AddField(
            model_name='suscriptor',
            name='es_suscriptor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='suscriptor',
            name='descuento',
            field=models.FloatField(default=0.0),
        ),
    ]
