# Generated by Django 3.1.2 on 2023-05-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20230520_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscriptor',
            name='descuento',
            field=models.FloatField(default=0.05),
        ),
    ]
