# Generated by Django 3.1.2 on 2023-05-21 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20230520_2055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suscriptor',
        ),
    ]
