# Generated by Django 3.1.2 on 2023-05-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_suscriptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suscriptor',
            name='descuento',
            field=models.FloatField(default=0.0),
        ),
    ]
