# Generated by Django 3.1.2 on 2023-05-21 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_suscriptor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suscriptor',
        ),
    ]
